### PR TITLE
Ability to modify the Pi's /boot/config.txt

### PR DESCRIPTION
**Pull request by ShadowLight8**
Ability to modify the Pi's /boot/config.txt
Specific items to cover:
- [X] Hardware vs Software I2C
- [x] Enable default PWM
- [x] Detect if PWM is already enabled and reflect that in option
- [x] Detect mismatch with hardware vs software I2C

Moving to another pull request:
- Select I2C pins
- Select PWM

### CODE REVIEW

**Comment by TomasRa1** [comment]
Nick, you are amazing!! It will be so nice, I am enjoying to result of your this perfect work! My dream come true thank's you!
It must take lot of your time, I would like to send you some money, please write me how can I donate this your the best work. We are already 2 who admire this your so inteligent and perfect work and who would like send you well-deserved reward.
Thank you so much for all! Tomas

**Comment by ShadowLight8** [comment]
> Nick, you are amazing!! It will be so nice, I am enjoying to result of your this perfect work! My dream come true thank's you! It must take lot of your time, I would like to send you some money, please write me how can I donate this your the best work. We are already 2 who admire this your so inteligent and perfect work and who would like send you well-deserved reward. Thank you so much for all! Tomas

Thank you Tomas! No need to send me any money, as this is my way to pay it forward to all those who have build the tools for this hobby. Your information and feedback is helpful to make this project better.

**Comment by chrkov** [comment]
Hey Nick,

Loving the new changes.   Maybe you overlooked this or just didnt get to it yet but you might want to update this wording since now a checkmark does all the work for you.   Nice Job!

image

**Comment by ShadowLight8** [comment]
@chrkov Good catch - I'll clean that up in the next PR

**Pull request merged**
