### PR TITLE
Various clean up tweaks and fixes

### PR DESCRIPTION
**Pull request by ShadowLight8**
Removed quite a few TODO comments and updated others. Fixed setting chip power. Better exception logging in callbacks. Added exception for json.loads.

### CODE REVIEW

**Comment by chrkov** [comment]
Running the latest version, it looks like you changed it where the Amp Power can be changed without a FPP Restart.  But I don't believe it is working without a restart.   I don't have a meter to prove it, all I have is I know my computer speakers will have a slight hum when the amp is at 100% because of there proximity to the antenna.   If I change the Amp power to 0, the hum remains until I do a FPP restart.   Same thing if I put it back to 100, the hum doesn't come back until I do a FPP restart.   So it would seem it still requires a restart of FPP to kick in.

**Comment by ShadowLight8** [comment]
I'll take a look tonight. There might be a second step I missed to get the new value to take effect.

**Comment by chrkov** [comment]
I am not sure where to put this.  Seems like a waste to open an issue.  But here is some more information I thought you might want to put on the main page, totally up to you.  Just some of the items I am using that seem to work well also.


Here is another antenna option.  I am using this one and it work really well.

https://www.aliexpress.us/item/2251832695723994.html?spm=a2g0o.productlist.main.1.5e6e72d5PorWDU&algo_pvid=ee2bbceb-b306-4e8b-8a35-81de3e5f6299&algo_exp_id=ee2bbceb-b306-4e8b-8a35-81de3e5f6299-0&pdp_npi=4%40dis%21USD%2119.10%2119.1%21%21%2119.10%21%21%40210318d117042463485862757e5205%2112000016437773400%21sea%21US%214256347821%21&curPageLogUid=ycAKOGjVlWlD


For the 1/4 wave antenna, here is a link to a calculator for the lengths to properly tune it.  

https://m0ukd.com/calculators/quarter-wave-ground-plane-antenna-calculator/


Here is another Amazon link for a 25' 50 ohm cable with BNC plugs that works with the above antenna.

https://www.amazon.com/gp/product/B0BVVVRYZL/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1


Here is a Amazon link for the connectors that comes with a crimper also.   This is the one I purchased and worked perfectly.

https://www.amazon.com/gp/product/B094XSF2GK/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Again, just some additional information if you want to use it.

**Comment by ShadowLight8** [comment]
> Running the latest version, it looks like you changed it where the Amp Power can be changed without a FPP Restart. But I don't believe it is working without a restart. I don't have a meter to prove it, all I have is I know my computer speakers will have a slight hum when the amp is at 100% because of there proximity to the antenna. If I change the Amp power to 0, the hum remains until I do a FPP restart. Same thing if I put it back to 100, the hum doesn't come back until I do a FPP restart. So it would seem it still requires a restart of FPP to kick in.

@chrkov I forgot that this is expected behavior with FPP 7.4. There was a FPP bug that I've submitted and has already been added to the master branch that fixes this, so I'm guessing it will be 7.5 or 8.0 before it is included. A short term option would be to switch your Git Branch to Master for now:
image

**Comment by chrkov** [comment]
I will jump over to the master branch and test it.   I saw your note on this for changing the PWM pin.  Didn't know it also affected this.

**Comment by ShadowLight8** [comment]
> I will jump over to the master branch and test it. I saw your note on this for changing the PWM pin. Didn't know it also affected this.

@chrkov Now I'm second guessing myself. I'll double check this. First day back at work after a long vacation and I can't remember anything :-P

**Comment by chrkov** [comment]
Nope, you are right.   On the Master branch now and it changes instantly.

But I also tried moving PWM to pin 32 (GPIO12) and that doesn't appear to be working.   My power doesn't seem to change at all using pin 32.

**Comment by ShadowLight8** [comment]
@chrkov No worries! Thanks for testing it out and reporting up issues. Glad it was as easy as shifting a pin.

It did get me thinking and I added a small tweak so that the Amp Power changing should now work under 7.4 (still a short term fix since I just force the update when the api is called no matter what).

**Pull request merged**
